### ISSUE TITLE
仓库文件夹只需要guess game一个就可以了噢

### ISSUE THREAD

**Issue by KKould** [ckpjasher/Rust-Lab#1]
这边看到代码实现了没错，不过可能围绕一个Lab新建太多文件夹了，看起来可能比较多，建议只使用guess game一个文件夹完成所有题目就好了
还有就是使用Git的一个小问题，你这边把target文件夹也提交上来了，解释一下target是你本机编译出来的实际运行程序，但其他人clone你这份仓库后，你仓库内的target文件夹是无效的，需要重新编译(而且target文件夹占用空间很大，可能会上几十m或者g)，可以了解下.gitignore文件的作用去忽略掉这个文件夹

**Comment by ckpjasher** [comment]
好的，已忽略并完成四个题干




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ckpjasher/Rust-Lab"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月2日(星期四) 晚上8:23
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ckpjasher/Rust-Lab] 仓库文件夹只需要guess game一个就可以了噢 (Issue #1)





 
这边看到代码实现了没错，不过可能围绕一个Lab新建太多文件夹了，看起来可能比较多，建议只使用guess game一个文件夹完成所有题目就好了
 还有就是使用Git的一个小问题，你这边把target文件夹也提交上来了，解释一下target是你本机编译出来的实际运行程序，但其他人clone你这份仓库后，你仓库内的target文件夹是无效的，需要重新编译(而且target文件夹占用空间很大，可能会上几十m或者g)，可以了解下.gitignore文件的作用去忽略掉这个文件夹

**Comment by KKould** [comment]
这边看你可能还没push上来，还是没变化，不过注意一下就好了，貌似没看到你有提交作业

**Comment by ckpjasher** [comment]
文件夹的话我会注意的，已经掌握了一些git指令了
在之后的项目里不会出现多个文件夹的问题（前提是项目功能简单）





2474727683
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ckpjasher/Rust-Lab"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月2日(星期四) 晚上8:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ckpjasher/Rust-Lab] 仓库文件夹只需要guess game一个就可以了噢 (Issue #1)





 
Closed #1 as completed.

**Comment by KKould** [comment]
emmm，不过其实有一点就是，git命令知道就好，尽可能直接使用idea或vscode的图形化git进行操作会比较方便

**Comment by ckpjasher** [comment]
hh，我其实就是想学一下git，我是jb老用户了，学生有jb全家桶的




2474727683
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ckpjasher/Rust-Lab"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月2日(星期四) 晚上8:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ckpjasher/Rust-Lab] 仓库文件夹只需要guess game一个就可以了噢 (Issue #1)





 
emmm，不过其实有一点就是，git命令知道就好，尽可能直接使用idea或vscode的图形化git进行操作会比较方便

**Comment by ckpjasher** [comment]
学长你好，我的学习通作业被批阅后第二天发现又回到待做状态，昨天又提交了一次，本来是待批阅，今天发现又回到待做的状态
今天又提交了一次，学长能帮我看看是怎么回事吗？
作业情况之前学长你跟我有交流过，并且当天帮我批阅了




2474727683
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ckpjasher/Rust-Lab"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月2日(星期四) 晚上8:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ckpjasher/Rust-Lab] 仓库文件夹只需要guess game一个就可以了噢 (Issue #1)





 
emmm，不过其实有一点就是，git命令知道就好，尽可能直接使用idea或vscode的图形化git进行操作会比较方便

**Comment by KKould** [comment]
好，我最近比较忙，晚几天帮你处理一下行吗

**Comment by ckpjasher** [comment]
好的，谢谢学长




2474727683
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ckpjasher/Rust-Lab"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月8日(星期三) 上午9:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ckpjasher/Rust-Lab] 仓库文件夹只需要guess game一个就可以了噢 (Issue #1)





 
好，我最近比较忙，晚几天帮你处理一下行吗
